# Generated by Django 4.0.4 on 2022-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='art_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
