# Generated by Django 4.0.3 on 2022-05-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhapp', '0002_artist_art_id_alter_artist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='some', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
