# Generated by Django 4.0.3 on 2022-05-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhapp', '0003_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
