# Generated by Django 4.0.3 on 2022-05-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhapp', '0005_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='city', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
