# Generated by Django 4.0.3 on 2022-05-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazakhapp', '0006_alter_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_photo',
            field=models.URLField(blank=True),
        ),
    ]
